version: 2.1
jobs:
  docker-medium-benchmark:
    docker:
      - image: cimg/base:current-22.04
    resource_class: arm.medium
    steps:
      - checkout
      - run: bash sysbench_setup.sh
      - run: bash run_sysbench.sh cpu arm.medium
      - run: bash run_sysbench.sh io arm.medium
      - run: bash run_sysbench.sh mem arm.medium
  docker-large-benchmark:
    docker:
      - image: cimg/base:current-22.04
    resource_class: arm.large
    steps:
      - checkout
      - run: bash sysbench_setup.sh
      - run: bash run_sysbench.sh cpu arm.large
      - run: bash run_sysbench.sh io arm.large
      - run: bash run_sysbench.sh mem arm.large

workflows:
  Benchmarks:
    jobs:
      - docker-medium-benchmark:
          filters:
            branches:
              only: circle-benchmark
      - docker-large-benchmark:
          filters:
            branches:
              only: circle-benchmark
