version: 2.1
jobs:
  docker-medium-benchmark:
    docker:
      - image: cimg/base:current-20.04
    resource_class: medium
    steps:
      - checkout
      - run: bash sysbench_setup.sh
      - run: echo "tests"
      - run: bash run_sysbench.sh cpu docker-medium
      - run: bash run_sysbench.sh io docker-medium
      - run: bash run_sysbench.sh mem docker-medium
  docker-large-benchmark:
    docker:
      - image: cimg/base:current-20.04
    resource_class: large
    steps:
      - checkout
      - run: bash sysbench_setup.sh
      - run: bash run_sysbench.sh cpu docker-large
      - run: bash run_sysbench.sh io docker-large
      - run: bash run_sysbench.sh mem docker-large

workflows:
  Benchmarks:
    jobs:
      - docker-medium-benchmark:
          filters:
            branches:
              only: circle-benchmark
      - docker-large-benchmark:
          filters:
            branches:
              only: circle-benchmark
