name: GitHub Actions Benchmark
on: [push]
jobs:
  Benchmark:
    runs-on: ubuntu-20.04
    steps:
      - run: cat /proc/cpuinfo
      - run: cat /proc/meminfo
      - run: mount
      - run: uname -a
      - run: sudo dmidecode -s system-manufacturer
      - run: sudo dmidecode -s system-product-name
      - run: lshw -class system
      - run: hostnamectl



