name: GitHub Actions Benchmark
on: [push]
jobs:
  Benchmark:
    runs-on: ubuntu-20.04
    steps:
      - run: cat /proc/cpuinfo
      - run: cat /proc/meminfo
      - run: mount
      - run: uname -a

